### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by kiddingchicken** [MigaMiDev/Mo-Than-Enough-Guns#1]
Whenever I try to reload without any munitions in my inventory, the game would just kick me out of my world. Game version: 1.20.1

**Comment by kiddingchicken** [comment]
![Capture d’écran 2024-08-18 214854](https://github.com/user-attachments/assets/0169452c-4ce4-4922-95aa-497b3023864c)

Weird that I get this as error message even tho im in singleplayer.

**Comment by MigaMiDev** [comment]
That is a issue with BackPacked mod, fixed on the newest unreleased version!
